trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - checkout: self
    clean: "true"
    persistCredentials: "true"

  - task: NodeTool@0
    displayName: "Install Node.js"
    inputs:
      versionSpec: "14.x"

  - bash: |
      echo ">>> Configure Git & NPM auth"
      git config --global user.name $(GIT_COMMITTER_NAME)
      git config --global user.email $(GIT_COMMITTER_EMAIL)
      git checkout main --progress --force
      echo -e "registry=https://registry.npmjs.org/\nalways-auth=true" >> .npmrc
      echo ">>> Build"
      npm ci
      npm run release
      echo "##vso[task.setvariable variable=latest_tag]$(git describe --tags --abbrev=0)"
      npm run remote:release
      npm run build
    displayName: "Build"
    condition: succeeded()
    env:
      GIT_COMMITTER_EMAIL: $(GIT_COMMITTER_EMAIL)
      GIT_COMMITTER_NAME: $(GIT_COMMITTER_NAME)

  - task: npmAuthenticate@0
    displayName: "Authenticate NPM"
    inputs:
      workingFile: .npmrc
      customEndpoint: npmjs.org_automation

  - task: Npm@1
    displayName: "Publish to NPM"
    inputs:
      command: publish
      publishRegistry: useExternalRegistry
      publishEndpoint: npmjs.org_automation

  - task: CopyFiles@2
    displayName: "Copy .mtar to staging directory"
    inputs:
      Contents: "mta_archives/**"
      TargetFolder: $(Build.ArtifactStagingDirectory)

  - task: GitHubRelease@0
    displayName: "Create GitHub release"
    inputs:
      gitHubConnection: github.com_leo-ls
      repositoryName: leo-ls/cf-destination-proxy
      action: create
      tagSource: manual
      tag: $(LATEST_TAG)
      releaseNotesSource: file
      releaseNotesFile: ./remote/RELEASE.md
      assets: $(Build.ArtifactStagingDirectory)/mta_archives/*.mtar
      isDraft: false
      addChangeLog: false

  - bash: git push --follow-tags origin main
    displayName: "Push results"
    condition: succeeded()
