trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - checkout: self
    clean: true
    persistCredentials: true

  - task: NodeTool@0
    displayName: "Install Node.js"
    inputs:
      versionSpec: "14.x"

  - bash: |
      echo ">>> Configure Git & NPM auth"
      git config --global user.name $(GIT_COMMITTER_NAME)
      git config --global user.email $(GIT_COMMITTER_EMAIL)
      git checkout main --progress --force
      echo "//registry.npmjs.org:_authToken=$NPM_TOKEN" >> .npmrc
      echo ">>> Build"
      npm install
      npm run release
      npm publish
      npm run build
      echo ">>> Push results"
      git push --follow-tags origin main
    displayName: "Build"
    condition: succeeded()
    env:
      GIT_COMMITTER_EMAIL: $(GIT_COMMITTER_EMAIL)
      GIT_COMMITTER_NAME: $(GIT_COMMITTER_NAME)
      NPM_TOKEN: $(NPM_TOKEN)

  - task: CopyFiles@2
    displayName: "Copy .mtar to staging directory"
    inputs:
      contents: "mta_archives/**"
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: GitHubRelease@0
    displayName: "Create GitHub release"
    inputs:
      gitHubConnection: github.com_leo-ls
      repositoryName: leo-ls/cf-destination-proxy
      action: create
      isDraft: false
